### ISSUE TITLE
Specifying both --html and --name <name>.html gives confusing results, if <name> is not 'license'

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#144]
I've just run the following:

```
license-reporter --unified-list --ignore-version-range --all --silent --html --file licenses.html
```

I was confused to see that the newly created `licenses.html` contained xml content rather than html content. Looking more closely, the following 3 files were created:

```
license.html
licenses.css
licenses.html
```

`license.html` had the html content, and `licenses.html` had the xml content.

**Comment by helio-frota** [comment]
@grdryn thanks for report it!

Not related but, if you do not need an external file for unified list, you can omit the `--unified-list` argument. Since we removed black/white lists the unified-list is the default now.

**Comment by helio-frota** [comment]
> ...newly created licenses.html contained xml content...

yah

```js
  if (options.file) {
    fs.writeFileSync(options.file, createdXml);
  }
```

`options.file` is the `--file`, and we are using this for the generated file name with XMl content, that's why you have `licenses.html` with xml content.

We can cut the `name` from extension and add the fixed `.xml` later, so when the user run this :

`license-reporter --file fooBar.cpp` will get a `fooBar.xml`

About the:
```
licenses.css
licenses.html
```

Both are hard-coded : 

` fs.writeFileSync('license.html', output); ` and `.pipe(fs.createWriteStream(path.join(options.directory, 'licenses.css')));`

I'm going to close this and open a new one to separate the name from extension and keep `.xml` hard coded.
